[versions]
agp = "9.2.1"
coreKtx = "1.15.0"
kotlin = "2.2.10"
libxposed = "102.0.0"
provider = "0.1.70"
composeBom = "2026.03.00"
activityCompose = "1.13.0"
miuix = "0.8.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
miuix = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed" }
lyricon-provider = { module = "io.github.proify.lyricon:provider", version.ref = "provider" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
